apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpy-ketzv1-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ketzv1-core
  template:
    metadata:
      labels:
        app: ketzv1-core
    spec:
      containers:
        - name: ketzv1-core
          image: us.gcr.io/vdbx-dev/core
          env:
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: secret-ketz-jwt
                  key: jwt
            - name: MONGO_URI
              value: 'mongodb://serv-ketzv1-core-mongo:27017/core'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://serv-nats:4222'
            - name: NATS_CLUSTER_ID
              value: ketketz
            
---
apiVersion: v1
kind: Service
metadata:
  name: serv-ketzv1-core
spec:
  selector:
    app: ketzv1-core
  ports:
  - name: ketzv1-core
    protocol: TCP
    port: 9998
    targetPort: 9998
