apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpy-ketzv1-cadence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ketzv1-cadence
  template:
    metadata:
      labels:
        app: ketzv1-cadence
    spec:
      containers:
        - name: ketzv1-cadence
          image: us.gcr.io/vdbx-dev/cadence
          env:
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: secret-ketz-jwt
                  key: jwt
            - name: MONGO_URI
              value: 'mongodb://serv-ketzv1-cadence-mongo:27017/cadence'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://serv-nats:4222'
            - name: NATS_CLUSTER_ID
              value: ketketz
            - name: REDIS_HOST
              value: srv-redis-bull
---
apiVersion: v1
kind: Service
metadata:
  name: serv-ketzv1-cadence
spec:
  selector:
    app: ketzv1-cadence
  ports:
  - name: ketzv1-cadence
    protocol: TCP
    port: 9997
    targetPort: 9997
